version: '2'
services:
    gamestransaction-app:
        image: gamestransaction
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://gamestransaction-mariadb:3306/gamestransaction
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gamestransaction-mariadb:
        extends:
            file: mariadb.yml
            service: gamestransaction-mariadb
